baseURL = "https://prertik.github.io"
languageCode = "en-us"
title = "(recur code)"
theme = "papercss-hugo-theme"
paginate = 10

enableRobotsTXT = true
googleAnalytics = "UA-108523579-1"
disqusShortname = "prertik-github-io"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
    author = "Pratik Karki"
    powered_by = false
    show_menu = true
    homeMetaContent = "A lazy hackers blog"
    dateFormat = "Jan 2, 2006"

[taxonomies]
tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home"
    weight = 1
    url = "/"
  [[menu.nav]]
    name = "About"
    weight = 2
    url = "/about/about/"
  [[menu.nav]]
    name = "Tags"
    weight = 3
    url = "/tags/"
  [[menu.nav]]
    name = "RSS"
    weight = 4
    url = "/index.xml"
