baseURL = "https://prertik.github.io"
languageCode = "en-us"
title = "(recur code)"
theme = "ezhil"
copyright = "© Copyright notice"
paginate = 10

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true
googleAnalytics = "UA-108523579-1"
disqusShortname = "prertik-github-io"

# [permalinks]
#   post = "/:filename/"

[imaging]
  quality = 99

[params]
    subtitle = "Writings on Coding and Life"
    #author = "Pratik Karki"
    avatar = "https://avatars0.githubusercontent.com/u/12194950?s=460&v=4"
    powered_by = false
    featherIconsCDN = true
    # Content types to disable Disqus on.
	  disableDisqusTypes = ["page"]
    #show_menu = true
    #homeMetaContent = "A lazy hackers blog"
    #dateFormat = "Jan 2, 2006"
    mode = "auto"

[taxonomies]
    tag = "tags"

[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "About"
weight = 2
url = "/about/about"

[[menu.main]]
name = "NSFW"
weight = 3
url = "/nsfw"

[[menu.main]]
name = "All posts"
weight = 4
url = "/posts"

[[menu.main]]
name = "Tags"
weight = 5
url = "/tags"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/prertik"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
