baseURL = "https://prertik.github.io"
languageCode = "en-us"
title = "(recur code)"
theme = "after-dark"
paginate = 10

enableRobotsTXT = true
googleAnalytics = "UA-108523579-1"
disqusShortname = "prertik-github-io"
SectionPagesMenu = "main"

[params]
    author = "Pratik Karki"
    powered_by = false
    show_menu = true
    theme_variant = "hack light"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Extra Writings"
    weight = 4
    identifier = "ewrites"
    url = "/categories/ewrites/"

[[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/about/"

[[menu.main]]
    name = "Git"
    weight = 3
    identifier = "git"
    url = "/categories/git/"

